spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poet?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  freemarker:
    prefix: /
  redis:
    port: 8081
mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*Mapper.xml
  type-aliases-package: com.baizhi.entity

